name: tasklyai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  awesome_dialog: ^3.3.0
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  image_picker: ^1.2.1
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
